name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    # see https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      # see https://www.npmjs.com/package/gh-pages
      - name: Deploy with gh-pages
        # see https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables
        # see https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm run deploy -- -u "github-actions-bot <support+actions@github.com>"
